# Generated by Django 4.1 on 2022-08-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('parentezco', models.CharField(max_length=30)),
                ('fecha_de_cumpleaños', models.DateField()),
            ],
        ),
    ]
