# Generated by Django 4.1 on 2022-08-31 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMVT', '0002_alter_familia_nombre_alter_familia_parentezco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familia',
            name='fecha_de_cumpleaños',
        ),
    ]
