# Generated by Django 4.1 on 2022-09-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMVT', '0003_remove_familia_fecha_de_cumpleaños'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='fecha_de_cumpleaños',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
